# Generated by Django 4.1.1 on 2022-12-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField(max_length=50)),
                ('ename', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
