# Generated by Django 4.1.1 on 2022-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIViewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.IntegerField(),
        ),
    ]
